apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0002
spec:
  storageClassName: host-volume
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Mi
  hostPath:
    path: /data/pv0002/
  claimRef: null